### ISSUE TITLE
Audio glitches using NAudio

### ISSUE THREAD

**Issue by amruyg** [Pixie1001/Battleships#11]
The NAudio branch seems to fix #10 and has all sound effects, but some of them sound glitchy (especially the "invalid location" sound made on the deployment screen when attempting to place one ship on top of another). The effect sounds louder and distorted near the end; is it being played twice?

**Comment by Pixie1001** [comment]
Hmm, oh yeah now that I compare it to the .cs version on my desktop audio, it does sound kinda off :/

Also, whatever I did in the NAudio version seems to have created a noticeable delay when hitting the Play button.

I'll mess around with it and see what the best solution is - but maybe we keep using SwinGame for the sound effects, and just don't release them? C# probably handles that automatically anyway.

And then we can use NAudio for the looping music,

**Comment by Pixie1001** [comment]
Ok, update - I have no idea why the error sound effect is glitching up - none of the other sounds appear to play any differently, and after adding like 200ms of dead air to the end of the error soundbite in Audacity, the issue clears up entirely.

I think maybe NAudio just doesn't like short sound files? Anyway, I'm not super happy with the solution of having to edit the soundfile itself because of an issue with a function, but this project is dumb and everything else is already a mess, so I vote to say the issue is fixed XD
